### ISSUE TITLE
Wrapping an entire code in MPIPool and using pytest

### ISSUE THREAD

**Issue by bernstei** [mpipool/mpipool#8]
I have a perhaps odd use case, where I want to wrap entire codes in a single MPIPool, and it is not really practical to put all the substantive parts of the code in a single `try..finally` or `with` block (like the README.md examples).   There's lots of arbitrary stuff, and interspersed are calls to map for a single `pool = MPIPool()` (or `MPIExecutor`) which is initialized at the beginning of the whole script. 

Before I started trying to use pytest, I've used the following scheme, which seemed to be working OK
```
def shutdown_and_barrier(pool, comm):
    pool.shutdown()
    comm.Barrier()

pool = MPIExecutor()
if pool.is_worker():
   MPI.COMM_WORLD.Barrier()
   exit()

atexit.register(shutdown_and_barrier, pool, MPI.COMM_WORLD)

[rank=0 continues here, doing various things including pool.map]
```
However, when I try to use the same scheme with pytest, I can't get it to work.  I create the pool with code like above in a fixture, defined in `conftest.py`, decorated with `@pytest.fixture(scope="session", autouse=True)`.  It seems to work until it's time to exit.  Then pytest complains about the SystemExit exception:
```
wfl/mpipool_support.py:41: in init
    exit()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Use exit() or Ctrl-D (i.e. EOF) to exit, code = None

    def __call__(self, code=None):
        # Shells like IDLE catch the SystemExit, but listen when their
        # stdin wrapper is closed.
        try:
            sys.stdin.close()
        except:
            pass
>       raise SystemExit(code)
E       SystemExit: None

/home/Software/python/anaconda3/lib/python3.8/_sitebuiltins.py:26: SystemExit
.
.
.
=========================== short test summary info ============================
ERROR tests/test_autopara_thread_vs_mpi.py::test_run - SystemExit: None
=============================== 1 error in 6.80s ===============================
```

Does anyone have any suggestions of getting my general scheme to work both with arbitrary scripts and with pytest?

**Comment by bernstei** [comment]
OK, I think I figured it out.  All the MPI processes have to report success for all the test to pass.  I had to slightly modify my init routine to make it possible to return after the worker barrier, instead of exiting, and make sure all the tests do nothing on the workers (since they only run after the actual worker tasks are done).

**Comment by Helveg** [comment]
The documentation is pretty sparse, mea culpa. Your use case seems entirely valid! There are multiple use cases when people want to start a pool, with the main going through a messy code path (so `with` not suited) and their program ends when the pool shuts down.

I'll take a look at how you solved this to improve the idiom for such use cases! Would `rejoin=False` have helped?

https://github.com/mpipool/mpipool/blob/a5d8eca9d058972a9ac8ede44d68237b451f3619/mpipool/_futures.py#L56-L75

**Comment by Helveg** [comment]
It seems like the only thing missing is for you to specify that the main and workers had to execute a `Barrier` before shutting down collectively.

Maybe `rejoin` can be slightly modified to be `True` (workers join and program continues) `False` (workers exit at pool shutdown) or a callable (workers execute the callable on pool shutdown, then rejoin).

You could then pass a callable to `rejoin` that `Barrier`s and `exit`s
